FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update

RUN apt-get install -y apt-utils vim curl apache2 apache2-utils
RUN apt-get -y install python3 libapache2-mod-wsgi-py3
RUN ln /usr/bin/python3 /usr/bin/python
RUN apt-get -y install python3-pip
# RUN ln /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip
RUN pip install django ptvsd

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE=1
RUN mkdir /code/
RUN mkdir /var/log/cc-logs/
RUN touch /var/log/cc-logs/generator.log
RUN chmod 777 /var/log/cc-logs/generator.log



WORKDIR /code/
COPY ./cc-backend/requirements.txt /code

COPY ./cc-backend/env/lib/python3.8/site-packages/docker /code
RUN pip install -r requirements.txt
RUN pip install docker
COPY ./cc-backend/ /code/
ADD ./cc-backend/site.conf /etc/apache2/sites-available/demo_site.conf
ADD ./cc-backend/ports.conf /etc/apache2/ports.conf
RUN a2ensite demo_site.conf
RUN a2enmod proxy
RUN a2enmod proxy_http
RUN a2enmod proxy_balancer
RUN a2enmod lbmethod_byrequests
RUN service apache2 start
# RUN service apache2 reload
EXPOSE 8080 3500

CMD ["apache2ctl", "-D", "FOREGROUND"]

