# stage1 as builder
FROM node:12-alpine as builder

# copy the package.json to install dependencies
COPY ./cc-frontend/package.json ./cc-frontend/package-lock.json ./

# Install the dependencies and make the folder
RUN npm install --legacy-peer-deps && mkdir /react-ui 

WORKDIR /react-ui
COPY ./cc-frontend .

# Build the project and copy the files
RUN npm run-script build
FROM nginx:alpine

#!/bin/sh
COPY ./cc-frontend/.nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the stage 1
COPY --from=builder /react-ui/dist/apps/control-center /usr/share/nginx/html
EXPOSE 3000 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]